version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - app_data:/code
    ports:
      - '80:80'

  admin:
    build:
      context: .
    volumes:
      - app_data:/code
    environment:
      - FLASK_APP=app.admin
    ports:
      - "5000:5000"
    entrypoint: ["make", "admin"]

volumes:
  app_data: